export const sample_foods = [
  {
    id: "1",
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Meatball",
    cookTime: "20-30",
    price: 20,
    favorite: false,
    origins: ["usa"],
    stars: 3.8,
    imageUrl: "food-2.jpg",
    tags: ["FastFood", "Meat", "Lunch"],
  },
  {
    id: "3",
    name: "Hamburger",
    cookTime: "15-25",
    price: 8,
    favorite: false,
    origins: ["usa"],
    stars: 4.2,
    imageUrl: "food-3.jpg",
    tags: ["FastFood", "Hamburger", "Lunch"],
  },
  {
    id: "4",
    name: "Salad",
    cookTime: "5-10",
    price: 6,
    favorite: false,
    origins: ["usa"],
    stars: 4.7,
    imageUrl: "food-4.jpg",
    tags: ["Salad", "Lunch"],
  },
  {
    id: "5",
    name: "Pasta Carbonara",
    cookTime: "15-20",
    price: 12,
    favorite: false,
    origins: ["italy"],
    stars: 4.9,
    imageUrl: "food-5.jpg",
    tags: ["Pasta", "Italian", "Lunch"],
  },

  // more food objects...
];
